In [25]:
class Employee:
    EmpNum = 0
    
    def __init__(self, name, family_name, salary, department):
        self.Name = name
        self.FamilyName = family_name
        self.Salary = salary
        self.Department = department
        Employee.EmpNum += 1
        
    def averagesalary(s):
        
        sum = 0
        for employee in s:
            sum += employee.Salary
        return sum / Employee.EmpNum
    
class FulltimeEmployee(Employee):
    def __init__(self,name,family_name,salary,department):
        super().__init__(name,family_name,salary,department)
    def Benefits(self):
        print("Few benefits as full time employee")
        
        
def main():
    employees = []
    e1 = FulltimeEmployee("Jk","k",1234566,"Development")
    e1.Benefits()
    employees.append(e1)
    e2 = FulltimeEmployee("abc","def",1234,"telemarketing")
    employees.append(e2)
    e3 = FulltimeEmployee("ghi","jkl",1234,"Testing")
    employees.append(e3)
    e4 = FulltimeEmployee("web","tec",12345,"Rescource management")
    employees.append(e4)
    print("average salary =", FulltimeEmployee.averagesalary(employees))
    
if __name__ == "__main__":
    main()

Few benefits as full time employee
average salary = 312344.75


Q1 DESCRIPTION
In the above code,
1.Created a variable to count the employees
2.Created a constructor in employees class and intialized variables in the constructor
3.Created a method averagesalary to calculate avarage salary with the formula - > Sum of salaries of all employees/ total number of employees
4.Used for loop to calculate the sum of salaries 
5.Created FulltimeEmployee which inherits form employee class
6.In the main methos, created a empty list employees
7.Added values to the list using append methods
8.Printed average salary, Called averagesalary method

In [28]:
import numpy as np
a = np.random.uniform(1,20,20)
print(a)

import numpy as np

Vector = a;

print("Array : " + str(Vector))

n = Vector.size

N = 4

M = n//N
reshaped = Vector.reshape((N, M))
print("First Reshaped Array 4 x 5 : ")
print(reshaped)
a = reshaped
b = a
b[np.arange(len(a)), a.argmax(1)] = 0
print(b)

[16.64507694 11.75535126  3.62764565  2.48413036  7.61546065  6.17938396
  7.19158967 17.8637294   6.8063506   1.1401625  15.56174091 15.58965967
  8.06913893  1.10193436  3.8068731  17.70083543 14.2773473   9.44897052
  9.76411921  9.86425805]
Array : [16.64507694 11.75535126  3.62764565  2.48413036  7.61546065  6.17938396
  7.19158967 17.8637294   6.8063506   1.1401625  15.56174091 15.58965967
  8.06913893  1.10193436  3.8068731  17.70083543 14.2773473   9.44897052
  9.76411921  9.86425805]
First Reshaped Array 4 x 5 : 
[[16.64507694 11.75535126  3.62764565  2.48413036  7.61546065]
 [ 6.17938396  7.19158967 17.8637294   6.8063506   1.1401625 ]
 [15.56174091 15.58965967  8.06913893  1.10193436  3.8068731 ]
 [17.70083543 14.2773473   9.44897052  9.76411921  9.86425805]]
[[ 0.         11.75535126  3.62764565  2.48413036  7.61546065]
 [ 6.17938396  7.19158967  0.          6.8063506   1.1401625 ]
 [15.56174091  0.          8.06913893  1.10193436  3.8068731 ]
 [ 0.         14.2773473   9.4

Q2 DESCRIPTION
In the above code
1.Imported numpy
2.Created a vector which has random float variables form 1 to 20
3.Created a variable to store the length and created a n integer with value 4
5.Reshaped the array to 4*5 matrix
6.Replaced the maximum value of all the rows to 0